id = "raylang"
name = "raylang"
version = "0.1.2"
schema_version = 1
authors = ["Roberto Ayala <dev@rayala.org>"]
description = "raylang language support: syntax highlighting, outline and the ray language server"
repository = "https://github.com/ray-language/zed-raylang"

[language_servers.ray-lsp]
name = "ray LSP"
languages = ["raylang"]

[grammars.raylang]
repository = "https://github.com/ray-language/tree-sitter-raylang"
rev = "d20f8e710c814db3dfd44cc2220343f94eb5d27d"
