id = "raylang"
name = "raylang"
version = "0.1.1"
schema_version = 1
authors = ["Roberto Ayala <dev@rayala.org>"]
description = "raylang language support: syntax highlighting, outline and the ray language server"
repository = "https://github.com/ray-language/zed-raylang"

[language_servers.ray-lsp]
name = "ray LSP"
languages = ["raylang"]

[grammars.raylang]
repository = "https://github.com/ray-language/tree-sitter-raylang"
rev = "b423d4486a6769427ba68cee1d99da7e3182d708"
